#!/usr/bin/perl

# This file is part of UCESB - a tool for data unpacking and processing.
#
# Copyright (C) 2016  Haakan T. Johansson  <f96hajo@chalmers.se>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301  USA

use strict;
use warnings;

print <<"EndOfText";

/*************************************************************
 *
 * This file is generated by $0 - do not edit.
 */

EndOfText

my %varnames = ();

my $branch = 0;

while(my $line = <>)
{
    chomp $line;
    if ($line =~ /^(\d)(\d)(\d)20000$/)
    {
	my $sam = $1;
	my $gtb = $2;
	my $sid = $3;

	my $varname = "_sst_ped_add_branch${branch}sam${sam}gtb${gtb}sid${sid}";
	$varnames{"[$branch][$sam][$gtb][$sid]"} = $varname;

	print ("uint32 ${varname}[1024] = {\n");
	for (my $i = 0; $i < 1024; $i += 16) {
	    my $valline = <>;

	    my @values = split ' ',$valline;

	    print ("  ");

	    for (my $j = 0; $j < 16; $j ++) {
		my $index = $i + $j;
		my $value = hex($values[$j]) >> 3;
		print "$value,";
	    }
	    print ("\n");
	}
	print ("};\n\n");
    }
    if ($line =~ /branch\s*(\d+)/)
    {
	$branch = $1;

    }
}

print <<"EndOfText";

\#include <memory.h>

uint32 *_sst_ped_add[4][16][2][16];

void init_sst_ped_add()
{
  memset(_sst_ped_add,0,sizeof(_sst_ped_add));

EndOfText

foreach my $key (sort keys %varnames) {
    my $varname = $varnames{$key};
    print ("  _sst_ped_add$key = $varname;\n");
}

print ("}\n");
